import { test, expect } from '@playwright/test';
import { loginAs } from './helpers/auth';
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';

dotenv.config({ path: path.resolve(process.cwd(), '.env') });

test.describe('Joiner Check-in Flow', () => {

  test.beforeEach(async () => {
    // Clean up any active sessions before running this test
    const url = process.env.SUPABASE_URL;
    const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
    if (url && key) {
      const supabase = createClient(url, key, { auth: { persistSession: false } });
      const { data: sessions } = await supabase
        .from('sessions')
        .select('id')
        .eq('is_active', true);
        
      if (sessions && sessions.length > 0) {
        for (const s of sessions) {
          await supabase.from('sessions')
            .update({ is_active: false, date_closed: new Date().toISOString(), close_notes: 'E2E cleanup before checkin test' })
            .eq('id', s.id);
        }
      }
    }
  });

  test('should allow joiner to check in and show up on host list', async ({ browser }) => {
    // Seed: assign both Budi (host) and Siti (joiner) to TPA-002 so the
    // ExpectedTeacherSelector has teachers to render.
    {
      const url = process.env.SUPABASE_URL!;
      const key = process.env.SUPABASE_SERVICE_ROLE_KEY!;
      const supabase = createClient(url, key, { auth: { persistSession: false } });
      const { data: users } = await supabase.from('users').select('id, nim');
      for (const nim of ['20521001', '20521002']) {
        const u = users?.find((x: any) => x.nim === nim);
        if (u) {
          await supabase.from('pengajar_tpa').delete().eq('user_id', u.id);
          await supabase.from('pengajar_tpa').insert({ user_id: u.id, tpa_id: 'tpa-002' });
        }
      }
    }

    // 1. Host logs in and opens session at TPA Adz-Dzikro (TPA-002)
    const hostContext = await browser.newContext({
      permissions: ['geolocation'],
      geolocation: { latitude: -7.7458065, longitude: 110.4090801 }
    });
    const hostPage = await hostContext.newPage();
    await loginAs(hostPage, '20521001', '23523198uam'); // Budi Santoso
    
    await hostPage.goto('/pengajar/scan');
    await hostPage.getByRole('button', { name: /Izinkan Akses Lokasi/i }).click();

    // Wait until simulate helper is ready
    await hostPage.waitForFunction(() => typeof (window as any).__simulateQRScan === 'function', { timeout: 10000 });

    // Host scans static QR TPA-002 to open session
    await hostPage.evaluate(() => {
      (window as any).__simulateQRScan('TPA-002');
    });

    // New flow: select expected teachers then click "Buka Sesi"
    await expect(hostPage.getByText(/Pilih Pengajar yang Wajib Hadir/i)).toBeVisible({ timeout: 10000 });
    await expect.poll(async () => {
      return await hostPage.locator('input[type="checkbox"]').count();
    }, { timeout: 15000, message: 'checkboxes should appear' }).toBeGreaterThanOrEqual(1);
    await hostPage.locator('input[type="checkbox"]').first().check();
    await hostPage.getByRole('button', { name: /Buka Sesi/i }).click();

    // Verify host gets redirected to active session screen
    await expect(hostPage).toHaveURL(/.*\/pengajar\/session\/.*/, { timeout: 15000 });

    // Extract the dynamic token from the QR element
    const qrImage = hostPage.locator('img[data-qr-token]');
    await expect(qrImage).toBeVisible({ timeout: 10000 });
    const qrTokenData = await qrImage.getAttribute('data-qr-token');
    expect(qrTokenData).not.toBeNull();
    expect(qrTokenData).not.toBe('');

    // 2. Joiner logs in on another browser instance
    const joinerContext = await browser.newContext({
      permissions: ['geolocation'],
      geolocation: { latitude: -7.74582, longitude: 110.4091 } // ~15m from TPA Adz-Dzikro center
    });
    const joinerPage = await joinerContext.newPage();
    await loginAs(joinerPage, '20521002', '23523198uam'); // Siti Rahayu

    await joinerPage.goto('/pengajar/scan');
    await joinerPage.getByRole('button', { name: /Izinkan Akses Lokasi/i }).click();

    // Wait until simulate helper is ready on joiner page
    await joinerPage.waitForFunction(() => typeof (window as any).__simulateQRScan === 'function', { timeout: 10000 });

    // Simulate Joiner scanning the dynamic QR token generated by Host
    await joinerPage.evaluate((token) => {
      (window as any).__simulateQRScan(token);
    }, qrTokenData!);

    // Expect joiner page to redirect to confirmation page
    await expect(joinerPage).toHaveURL(/.*\/pengajar\/konfirmasi.*/, { timeout: 15000 });

    // Verify check-in success message on confirmation page
    await expect(joinerPage.getByText(/Presensi Masuk Berhasil!/i)).toBeVisible({ timeout: 10000 });

    // Click Kembali ke Dashboard to complete flow
    await joinerPage.getByRole('button', { name: /Kembali ke Dashboard/i }).click();
    await expect(joinerPage).toHaveURL(/.*\/pengajar\/dashboard/i, { timeout: 10000 });

    // 3. Real-time validation: Verify joiner's name (Siti Rahayu) appears dynamically on Host session screen
    await expect(hostPage.getByText('Siti Rahayu')).toBeVisible({ timeout: 15000 });

    await hostContext.close();
    await joinerContext.close();
  });

});
